### ISSUE TITLE
Style.css not included in a release zip file

### ISSUE THREAD

**Issue by zzdcgg** [mrjackphil/obsidian-zoom-in-headers#1]
Downloaded the latest zip file, unzipped and located it under the plugin folder, but it has not worked so far.  When trying zoom in, the file path showed up at the top, but the text did not change (see the 1st screenshot); also, when Ctrl+click, nothing happened (see the 2nd screenshot).  How to fix this?  Thanks!
<img width="755" alt="iShot2021-05-08 20 39 34" src="https://user-images.githubusercontent.com/70086177/117540647-b5d69080-b042-11eb-8242-8eecae0cedd0.png">
<img width="761" alt="iShot2021-05-08 20 40 27" src="https://user-images.githubusercontent.com/70086177/117540659-c129bc00-b042-11eb-8c67-f80c3a107839.png">

**Comment by mrjackphil** [comment]
The zip file missing the css file. CSS can be downloaded from release section separately, for now.

**Comment by zzdcgg** [comment]
Thanks!
